### ISSUE TITLE
for development: create some list of tasks

### ISSUE THREAD

**Issue by mszakacz** [kamilgadek/to_do_list_kamilg#10]
In tasks_repository create a separate file tasks_data and store there a list of tasks (few instances of the Task class).
It is only for development purposes, because you need it to UI development - for example TaskWidget woul require the Task instance, and the TasksPage would fetch a tasks - for now we would take these hard-coded tasks.
Just add the comment to this file that this file should be deleted, as it is created for development purposes only

**Comment by kamilgadek** [comment]
This file should be deleted, as it is created for development purposes only

**Comment by mszakacz** [comment]
Done in https://github.com/kamilgadek/to_do_list_kamilg/pull/18
