### ISSUE TITLE
Create a Theme, colors and text styles

### ISSUE THREAD

**Issue by mszakacz** [kamilgadek/to_do_list_kamilg#2]
Every app should have a theme.
Let's create such a class AppTheme which will contain a theme.

In the same folder let's create a class that will contain all the colors that your app will be using, let's name it AppColors.

At the end, in your app there will be some texts displayed, so we need a class which will store its styles, let's name it TextStyles.

**Comment by mszakacz** [comment]
@kamilgadek is it completed?

**Comment by kamilgadek** [comment]
Yes i showed you yesterday it, it's in theme folder:
<img width="1279" alt="Zrzut ekranu 2024-09-11 o 18 45 35" src="https://github.com/user-attachments/assets/b18fd9ca-e213-4985-8594-b5513caf5ddc">

**Comment by mszakacz** [comment]
done
