### ISSUE TITLE
GENERAL: Where to store tasks

### ISSUE THREAD

**Issue by mszakacz** [kamilgadek/to_do_list_kamilg#23]
@kamilgadek Let's use this issue to discuss where we wanna store out data.
Options:
1) Firebase
2) Device storage
3) Other DB + API ([free API](https://developer.todoist.com/guides/#designing-browser-extensions))

Based on the selection we will design a architecture.

Give me your opinion on every option, try to think about benefits and disadvantages of each approach.

**Comment by mszakacz** [comment]
@kamilgadek any update on this?

**Comment by kamilgadek** [comment]
I have got some experience in Firebase, so we can store our data there.

**Comment by mszakacz** [comment]
@kamilgadek 
Nice research. For this app let's go with Local Storage.
